KafkaServer {
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="admin"
    password="admin-password"
    user_admin="admin-password"
    user_tenant-acme="acme-password"
    user_tenant-globex="globex-password"
    user_tenant-initech="initech-password";
};
